apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - image: catalog:1.0
        imagePullPolicy: IfNotPresent
        name: catalog
        ports:
        - containerPort: 3000