apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - image: order:1.0
        imagePullPolicy: IfNotPresent
        name: order
        ports:
        - containerPort: 3001