apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: catalog-deploy-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalog-deploy
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 2
